<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Milestone;

class MilestoneSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {

        $imagePath = '/images/image-coming-soon.jpg';

        $milestones = [
            //Seeder for 1 months old
            [
                'id' => 1,
                'age_group' => 1,
                'domain' => 'tindak_balas_refleks',
                'isCritical' => true,
                'description' => 'Bayi menoleh ke arah pipi atau tepi mulutnya apabila disentuh atau diusap (Rooting Reflex).',
                'youtube_title' => 'Rooting Reflex in Newborn Infant Baby | Pediatric Nursing Assessment',
                'key' => 'QXGuGKL57xo',
                'image_path' => 'no',   
            ],
            [
                'id' => 2,
                'age_group' => 1,
                'domain' => 'tindak_balas_refleks',
                'isCritical' => false,
                'description' => 'Bayi mengenggam tangan sendiri (Grasp Reflex).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 3,
                'age_group' => 1,
                'domain' => 'tindak_balas_refleks',
                'isCritical' => true,
                'description' => 'Bayi menghisap susu dengan baik (Sucking Reflex).',
                'youtube_title' => 'Newborn Sucking Reflex in Infant | Pediatric Nursing Assessment Exam Skill',
                'key' => 'dOP6BhIHYTM',
                'image_path' => 'no',   
            ],
            [
                'id' => 4,
                'age_group' => 1,
                'domain' => 'motor_halus',
                'isCritical' => false,
                'description' => 'Menggenggam jari ibu bapa atau penjaga apabila jari ibu bapa atau penjaga diletakkan di tapak tangan bayi.',
                'youtube_title' => 'Palmar Grasp Reflex Reaction Infant Newborn Pediatric Nursing Assessment',
                'key' => 'IlbYFBEgpJI',
                'image_path' => 'no',   
            ],
            [
                'id' => 5,
                'age_group' => 1,
                'domain' => 'penglihatan',
                'isCritical' => true,
                'description' => 'Mengerdipkan mata apabila terdedah dengan cahaya dan apabila tangan ditepuk di hadapan muka.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 6,
                'age_group' => 1,
                'domain' => 'pendengaran',
                'isCritical' => true,
                'description' => 'Terkejut pada bunyi kuat.',
                'youtube_title' => 'Reacts to loud sounds',
                'key' => 'ZQ2tm9mvDG4',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 7,
                'age_group' => 1,
                'domain' => 'pertuturan_dan_bahasa',
                'isCritical' => true,
                'description' => 'Mengeluarkan bunyi (Cooing). Contoh: bunyi “aah, oo, gah, uu”.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 8,
                'age_group' => 1,
                'domain' => 'kelakuan',
                'isCritical' => false,
                'description' => 'Senyum secara spontan',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 9,
                'age_group' => 1,
                'domain' => 'kognitif',
                'isCritical' => false,
                'description' => 'Memandang muka ibu bapa atau penjaga pada jarak dekat.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 10,
                'age_group' => 1,
                'domain' => 'kognitif',
                'isCritical' => false,
                'description' => 'Melihat pergerakan objek atau orang pada jarak yang dekat (dengan jarak satu (1) lengan).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            
            //Seeder for 3 months old
            [
                'id' => 11,
                'age_group' => 3,
                'domain' => 'motor_kasar',
                'isCritical' => true,
                'description' => 'Menggerakkan seluruh anggota badan.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 12,
                'age_group' => 3,
                'domain' => 'motor_kasar',
                'isCritical' => true,
                'description' => 'Berupaya menegakkan kepala semasa didukung.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 13,
                'age_group' => 3,
                'domain' => 'motor_kasar',
                'isCritical' => false,
                'description' => 'Memaut jari-jemari ibu bapa atau penjaga apabila ditarik untuk duduk.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 14,
                'age_group' => 3,
                'domain' => 'motor_halus',
                'isCritical' => false,
                'description' => 'Memegang atau menggoncang mainan apabila diletak pada tangan dalam tempoh singkat (dalam tempoh lima (5) saat).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 15,
                'age_group' => 3,
                'domain' => 'motor_halus',
                'isCritical' => false,
                'description' => 'Membelek dan bermain jari jemari sendiri.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 16,
                'age_group' => 3,
                'domain' => 'penglihatan',
                'isCritical' => false,
                'description' => 'Memberi tumpuan kepada objek yang berada di sekeliling.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 17,
                'age_group' => 3,
                'domain' => 'pendengaran',
                'isCritical' => true,
                'description' => 'Menunjukkan respon dan memalingkan kepala mengikut arah sumber bunyi.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 18,
                'age_group' => 3,
                'domain' => 'pertuturan_dan_bahasa',
                'isCritical' => true,
                'description' => 'Menghasilkan bunyi seperti mengekek, mendengus atau menjerit.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 19,
                'age_group' => 3,
                'domain' => 'pertuturan_dan_bahasa',
                'isCritical' => false,
                'description' => 'Menangis atau merengek apabila tidak selesa, sakit atau lapar dan sebagainya.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 20,
                'age_group' => 3,
                'domain' => 'kelakuan',
                'isCritical' => false,
                'description' => 'Senyum atau membalas senyuman kepada ibu bapa atau penjaga.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 21,
                'age_group' => 3,
                'domain' => 'kognitif',
                'isCritical' => false,
                'description' => 'Memberi tindak balas apabila ibu bapa atau penjaga menggeletek dan bermain bersamanya.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],

            //Seeder for 6 months old
            [
                'id' => 22,
                'age_group' => 6,
                'domain' => 'motor_kasar',
                'isCritical' => true,
                'description' => 'Meniarap dan menelentang.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 23,
                'age_group' => 6,
                'domain' => 'motor_kasar',
                'isCritical' => false,
                'description' => 'Duduk dengan sokongan atau bantuan (dipegang oleh orang lain).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 24,
                'age_group' => 6,
                'domain' => 'motor_halus',
                'isCritical' => true,
                'description' => 'Boleh menggenggam objek (contoh: menggenggam permainan bersaiz kecil).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 25,
                'age_group' => 6,
                'domain' => 'penglihatan',
                'isCritical' => false,
                'description' => 'Mata mengikut arah objek yang digerakkan (contoh: kiri, kanan, atas dan bawah).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 26,
                'age_group' => 6,
                'domain' => 'pendengaran',
                'isCritical' => true,
                'description' => 'Menunjukkan reaksi kepada arah sumber bunyi daripada orang atau persekitaran (contoh: menoleh, menangis, terkejut atau terdiam).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 27,
                'age_group' => 6,
                'domain' => 'pertuturan_dan_bahasa',
                'isCritical' => false,
                'description' => 'Menyebut suku kata berulang kali (contoh: pa..pa..pa, ma..ma..ma).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 28,
                'age_group' => 6,
                'domain' => 'pertuturan_dan_bahasa',
                'isCritical' => false,
                'description' => 'Menghasilkan bunyi seperti ketawa, menjerit, mengekek dan bunyi tidak bermakna apabila diajak bercakap (contoh: aah... oo... mm… daa, menyembur air liur dan sebagainya).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 29,
                'age_group' => 6,
                'domain' => 'kelakuan',
                'isCritical' => false,
                'description' => 'Mengangkat tangan minta didukung.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 30,
                'age_group' => 6,
                'domain' => 'kelakuan',
                'isCritical' => false,
                'description' => 'Bermain sendiri seperti bermain jari jemari tangan dan kaki.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 31,
                'age_group' => 6,
                'domain' => 'kelakuan',
                'isCritical' => false,
                'description' => 'Memberi respons apabila melihat diri melalui cermin(contoh: senyum, ketawa).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 32,
                'age_group' => 6,
                'domain' => 'kognitif',
                'isCritical' => false,
                'description' => 'Boleh mencapai objek yang diletakkan di hadapan.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],

            //Seeder for 9 months old
            [
                'id' => 33,
                'age_group' => 9,
                'domain' => 'motor_kasar',
                'isCritical' => true,
                'description' => 'Duduk sendiri tanpa sokongan atau bantuan.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 34,
                'age_group' => 9,
                'domain' => 'motor_kasar',
                'isCritical' => false,
                'description' => 'Mula cuba untuk merangkak.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 35,
                'age_group' => 9,
                'domain' => 'motor_halus',
                'isCritical' => true,
                'description' => 'Memindahkan objek dari satu tangan ke tangan sendiri yang lain (contoh pindah objek dari tangan kiri ke tangan kanak-kanak dan sebaliknya).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],[
                'id' => 36,
                'age_group' => 9,
                'domain' => 'motor_halus',
                'isCritical' => false,
                'description' => 'Menyentuh, mencucuk atau mengutip objek kecil dengan menggunakan jari telunjuk dan ibu jari (Pincer Grasp).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 37,
                'age_group' => 9,
                'domain' => 'penglihatan',
                'isCritical' => false,
                'description' => 'Memerhati dan mengikut pergerakan objek yang sedang atau telah jatuh.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 38,
                'age_group' => 9,
                'domain' => 'pendengaran',
                'isCritical' => true,
                'description' => 'Mencari sumber bunyi persekitaran.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 39,
                'age_group' => 9,
                'domain' => 'pertuturan_dan_bahasa',
                'isCritical' => true,
                'description' => 'Meniru dan membuat bunyi pertuturan yang panjang (contoh: pa-pa-ba-da-ka-ba-ga dan sebagainya).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 40,
                'age_group' => 9,
                'domain' => 'pertuturan_dan_bahasa',
                'isCritical' => false,
                'description' => 'Memahami perkataan "tak boleh" dan "bye".',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 41,
                'age_group' => 9,
                'domain' => 'kelakuan',
                'isCritical' => false,
                'description' => 'Pandang apabila orang berinteraksi dengannya.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 42,
                'age_group' => 9,
                'domain' => 'kelakuan',
                'isCritical' => false,
                'description' => 'Menunjukkan reaksi yang berbeza apabila melihat ibu bapa atau penjaga dan orang lain (contoh senyum, berkerut, menyorok wajah, malu dan sebagainya).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 43,
                'age_group' => 9,
                'domain' => 'kelakuan',
                'isCritical' => false,
                'description' => 'Bermain ci-ku-cak (Peek-A-Boo).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 44,
                'age_group' => 9,
                'domain' => 'kognitif',
                'isCritical' => false,
                'description' => 'Manipulasi objek seperti mengetuk objek, menekan butang, menarik kain atau menjatuhkan objek secara sengaja.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 45,
                'age_group' => 9,
                'domain' => 'kognitif',
                'isCritical' => false,
                'description' => 'Memasukkan objek ke dalam mulut.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 46,
                'age_group' => 9,
                'domain' => 'kognitif',
                'isCritical' => false,
                'description' => 'Mencuba untuk mencapai objek yang jatuh.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],

            //Seeder for 12 months old
            [
                'id' => 47,
                'age_group' => 12,
                'domain' => 'motor_kasar',
                'isCritical' => false,
                'description' => 'Berdiri dengan bantuan.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 48,
                'age_group' => 12,
                'domain' => 'motor_kasar',
                'isCritical' => false,
                'description' => 'Berjalan sambil memegang sebelah tangan ibu bapa atau memaut pada perabot.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 49,
                'age_group' => 12,
                'domain' => 'motor_halus',
                'isCritical' => false,
                'description' => 'Menyelak muka surat pada buku yang tebal.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 50,
                'age_group' => 12,
                'domain' => 'motor_halus',
                'isCritical' => false,
                'description' => 'Menunjuk dengan jari telunjuk pada objek yang diminati.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 51,
                'age_group' => 12,
                'domain' => 'motor_halus',
                'isCritical' => true,
                'description' => 'Boleh mengutip objek kecil di sekitarnya tanpa meletakkan siku, lengan dan pergelangan tangan pada permukaan.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 52,
                'age_group' => 12,
                'domain' => 'penglihatan',
                'isCritical' => false,
                'description' => 'Memasukkan objek ke dalam lubang berdasarkan bentuk objek (contoh: shape shorter, insert puzzle).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 53,
                'age_group' => 12,
                'domain' => 'pendengaran',
                'isCritical' => false,
                'description' => 'Terus menoleh apabila nama dipanggil.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 54,
                'age_group' => 12,
                'domain' => 'pertuturan_dan_bahasa',
                'isCritical' => false,
                'description' => 'Boleh mengikut arahan mudah (contoh: mari sini, jom, bagi ayah, angkat tangan dan sebagainya).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 55,
                'age_group' => 12,
                'domain' => 'pertuturan_dan_bahasa',
                'isCritical' => false,
                'description' => 'Mula menggunakan sekurang-kurangnya satu perkataan mengikut situasi yang sesuai (perkataan hendaklah bermakna, contoh bola, mama, nak).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 56,
                'age_group' => 12,
                'domain' => 'kelakuan',
                'isCritical' => false,
                'description' => 'Melambai dan menepuk tangan.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 57,
                'age_group' => 12,
                'domain' => 'kelakuan',
                'isCritical' => false,
                'description' => 'Menghulurkan tangan apabila hendak dipakaikan baju dan kaki apabila hendak memakai seluar atau kasut.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 58,
                'age_group' => 12,
                'domain' => 'kognitif',
                'isCritical' => false,
                'description' => 'Mencari benda tersembunyi di pelbagai lokasi.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 59,
                'age_group' => 12,
                'domain' => 'kognitif',
                'isCritical' => false,
                'description' => 'Boleh menggunakan objek mengikut kegunaan yang betul (contoh: menggunakan sudu, sikat, cawan, telefon).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],

            //Seeder for 18 months
            [
                'id' => 60,
                'age_group' => 18,
                'domain' => 'motor_kasar',
                'isCritical' => true,
                'description' => 'Berjalan sendiri.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 61,
                'age_group' => 18,
                'domain' => 'motor_kasar',
                'isCritical' => false,
                'description' => 'Memanjat tangga, meja, kerusi dan lain-lain.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 62,
                'age_group' => 18,
                'domain' => 'motor_halus',
                'isCritical' => true,
                'description' => 'Menconteng menggunakan krayon, pensel atau pen.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 63,
                'age_group' => 18,
                'domain' => 'motor_halus',
                'isCritical' => false,
                'description' => 'Boleh membuka beberapa helaian muka surat buku.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 64,
                'age_group' => 18,
                'domain' => 'motor_halus',
                'isCritical' => false,
                'description' => 'Membina menara menggunakan tiga blok atau kiub mainan.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 65,
                'age_group' => 18,
                'domain' => 'penglihatan',
                'isCritical' => false,
                'description' => 'Memerhati pergerakan orang yang dikenali pada sesuatu jarak.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 66,
                'age_group' => 18,
                'domain' => 'penglihatan',
                'isCritical' => false,
                'description' => 'Boleh menunjuk (dengan jari) pada objek yang diminati di jarak yang jauh.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 67,
                'age_group' => 18,
                'domain' => 'penglihatan',
                'isCritical' => false,
                'description' => 'Suka melihat gambar-gambar dalam buku.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 68,
                'age_group' => 18,
                'domain' => 'pendengaran',
                'isCritical' => false,
                'description' => 'Menunjuk kepada objek atau gambar yang disebut oleh orang lain (contoh: ibu sebut kucing, anak tunjuk kucing).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 69,
                'age_group' => 18,
                'domain' => 'pertuturan_dan_bahasa',
                'isCritical' => false,
                'description' => 'Menggunakan sekurang-kurangnya 6 - 20 perkataan dalam rutin harian (perkataan hendaklah bermakna, contoh susu, air, makan dan tidur).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 70,
                'age_group' => 18,
                'domain' => 'pertuturan_dan_bahasa',
                'isCritical' => false,
                'description' => 'Menggabungkan dua perkataan dalam satu ayat pendek (contoh: nak susu, kucing tidur, jom main).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 71,
                'age_group' => 18,
                'domain' => 'kelakuan',
                'isCritical' => false,
                'description' => 'Memeluk anak patung atau patung haiwan.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 72,
                'age_group' => 18,
                'domain' => 'kelakuan',
                'isCritical' => false,
                'description' => 'Memegang dan minum menggunakan cawan tanpa bantuan.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 73,
                'age_group' => 18,
                'domain' => 'kelakuan',
                'isCritical' => false,
                'description' => 'Meniru aktiviti orang dewasa (contoh: lap meja, sikat rambut, menyapu dan lain-lain).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 74,
                'age_group' => 18,
                'domain' => 'kognitif',
                'isCritical' => true,
                'description' => 'Tidak lagi memasukkan objek ke dalam mulut.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 75,
                'age_group' => 18,
                'domain' => 'kognitif',
                'isCritical' => false,
                'description' => 'Menjatuhkan atau memasuk semula beberapa alat permainan atau objek ke dalam bekas, kotak, mangkuk dan sebagainya.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],

            //Seeder for 24 months old
            [
                'id' => 76,
                'age_group' => 24,
                'domain' => 'motor_kasar',
                'isCritical' => true,
                'description' => 'Berlari 10 kaki ke hadapan.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 77,
                'age_group' => 24,
                'domain' => 'motor_kasar',
                'isCritical' => false,
                'description' => 'Menolak dan menarik permainan beroda (contoh: basikal, kereta mainan).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 78,
                'age_group' => 24,
                'domain' => 'motor_kasar',
                'isCritical' => true,
                'description' => 'Cuba menyepak dan menendang bola bersaiz besar dengan perlahan.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 79,
                'age_group' => 24,
                'domain' => 'motor_halus',
                'isCritical' => false,
                'description' => 'Membina menara menggunakan tujuh blok atau kiub mainan.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 80,
                'age_group' => 24,
                'domain' => 'motor_halus',
                'isCritical' => false,
                'description' => 'Meniru lukisan garisan menegak (contoh: I).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 81,
                'age_group' => 24,
                'domain' => 'motor_halus',
                'isCritical' => false,
                'description' => 'Boleh memasukkan tali ke dalam lubang manik besar.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 82,
                'age_group' => 24,
                'domain' => 'penglihatan',
                'isCritical' => false,
                'description' => 'Menganggar ketinggian atau kedalaman (depth) sesuatu objek (contoh: apabila menurun katil, sofa, tangga atau melangkah lubang atau longkang).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 83,
                'age_group' => 24,
                'domain' => 'pertuturan_dan_bahasa',
                'isCritical' => false,
                'description' => 'Boleh mengikut arahan mudah (contoh: “Ambil bola di atas meja”).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 84,
                'age_group' => 24,
                'domain' => 'pertuturan_dan_bahasa',
                'isCritical' => true,
                'description' => 'Menunjuk atau menamakan gambar atau objek apabila ditanya oleh orang lain.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 85,
                'age_group' => 24,
                'domain' => 'pertuturan_dan_bahasa',
                'isCritical' => false,
                'description' => 'Sering meniru perkataan yang didengari daripada orang lain.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 86,
                'age_group' => 24,
                'domain' => 'kelakuan',
                'isCritical' => false,
                'description' => 'Bermain anak patung atau patung haiwan (contoh: memeluk, cium, memberi makanan kepada teddy bear atau anak patung).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 87,
                'age_group' => 24,
                'domain' => 'kelakuan',
                'isCritical' => false,
                'description' => 'Bermain berdekatan dengan orang lain tetapi tidak suka berkongsi permainan.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 88,
                'age_group' => 24,
                'domain' => 'kognitif',
                'isCritical' => false,
                'description' => 'Meletak semula barang di tempatnya (contoh: simpan mainan di dalam bekas mainan).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 89,
                'age_group' => 24,
                'domain' => 'kognitif',
                'isCritical' => false,
                'description' => 'Menggunakan 1 objek sebagai benda lain (contoh: alat kawalan jauh sebagai telefon, blok kayu sebagai kereta).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],

            //Seeder for 36 months old
            [
                'id' => 90,
                'age_group' => 36,
                'domain' => 'motor_kasar',
                'isCritical' => false,
                'description' => 'Cekap menggunakan kaki seperti melompat dan memanjat.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 91,
                'age_group' => 36,
                'domain' => 'motor_kasar',
                'isCritical' => false,
                'description' => 'Naik tangga berselang kaki tanpa bantuan.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 92,
                'age_group' => 36,
                'domain' => 'motor_halus',
                'isCritical' => false,
                'description' => 'Membina menara menggunakan 9 -10 kiub.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 93,
                'age_group' => 36,
                'domain' => 'motor_halus',
                'isCritical' => false,
                'description' => 'Boleh menyalin bentuk bulat.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 94,
                'age_group' => 36,
                'domain' => 'motor_halus',
                'isCritical' => false,
                'description' => 'Boleh menggunting hujung kertas (Snipping).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 95,
                'age_group' => 36,
                'domain' => 'pertuturan_dan_bahasa',
                'isCritical' => false,
                'description' => 'Mengikut dua peringkat arahan dalam satu masa (contoh: “letak beg atas meja dan susun kasut dalam rak”).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 96,
                'age_group' => 36,
                'domain' => 'pertuturan_dan_bahasa',
                'isCritical' => false,
                'description' => 'Boleh memberitahu nama penuh sendiri.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 97,
                'age_group' => 36,
                'domain' => 'pertuturan_dan_bahasa',
                'isCritical' => false,
                'description' => 'Membina ayat menggunakan tiga hingga empat perkataan dengan lancar (contoh: saya suka makan roti, ibu tolong buka pintu).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 98,
                'age_group' => 36,
                'domain' => 'kelakuan',
                'isCritical' => false,
                'description' => 'Bermain permainan olok-olok (Pretend Play) menggunakan objek bersama-sama kawan (contoh: bermain masak-masak, memandu kereta).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 99,
                'age_group' => 36,
                'domain' => 'kelakuan',
                'isCritical' => true,
                'description' => 'Boleh menyuap makanan ke mulut menggunakan sudu, garfu atau tangan dengan baik (kurang bersepah).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 100,
                'age_group' => 36,
                'domain' => 'kelakuan',
                'isCritical' => true,
                'description' => 'Boleh memakai dan menanggalkan baju t-shirt dan seluar tanpa bantuan.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 101,
                'age_group' => 36,
                'domain' => 'kognitif',
                'isCritical' => false,
                'description' => 'Memadankan dua atau tiga warna asas seperti warna merah, kuning, hijau.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 102,
                'age_group' => 36,
                'domain' => 'kognitif',
                'isCritical' => false,
                'description' => 'Menyelesaikan masalah mudah seperti mengambil kerusi untuk mencapai objek di tempat tinggi.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 103,
                'age_group' => 36,
                'domain' => 'kognitif',
                'isCritical' => false,
                'description' => 'Boleh mengecam bentuk asas △ ▭ ◯.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            
            //Seeder for 48 months old
            [
                'id' => 104,
                'age_group' => 48,
                'domain' => 'motor_kasar',
                'isCritical' => false,
                'description' => 'Lompat ke hadapan dengan sebelah kaki.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 105,
                'age_group' => 48,
                'domain' => 'motor_kasar',
                'isCritical' => false,
                'description' => 'Berlari laju dan berhenti tanpa jatuh.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 106,
                'age_group' => 48,
                'domain' => 'motor_kasar',
                'isCritical' => false,
                'description' => 'Turun tangga berselang kaki tanpa bantuan.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 107,
                'age_group' => 48,
                'domain' => 'motor_halus',
                'isCritical' => false,
                'description' => 'Meniru tanda palang ( + ).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 108,
                'age_group' => 48,
                'domain' => 'motor_halus',
                'isCritical' => false,
                'description' => 'Boleh melukis gambar orang yang mempunyai sekurang-kurangnya tiga daripada angggota badan seperti kepala, mata, hidung, mulut, leher, badan, rambut atau tangan.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 109,
                'age_group' => 48,
                'domain' => 'motor_halus',
                'isCritical' => false,
                'description' => 'Boleh menggunting kertas menjadi separuh dalam satu garisan lurus.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 110,
                'age_group' => 48,
                'domain' => 'pertuturan_dan_bahasa',
                'isCritical' => false,
                'description' => 'Menjawab soalan berkaitan aktiviti harian (contoh: Apa awak buat bila lapar? “Saya makan atau makan nasi”).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 111,
                'age_group' => 48,
                'domain' => 'pertuturan_dan_bahasa',
                'isCritical' => false,
                'description' => 'Boleh menerangkan dua perkara tentang sesuatu objek dengan jelas (contoh: Kereta ada empat tayar, kereta laju, kertas warna merah).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 112,
                'age_group' => 48,
                'domain' => 'pertuturan_dan_bahasa',
                'isCritical' => false,
                'description' => 'Boleh bertanya soalan mengguna soalan ‘apa?, kenapa? Bagaimana? (contoh: “Kenapa awak nangis?”).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 113,
                'age_group' => 48,
                'domain' => 'kelakuan',
                'isCritical' => false,
                'description' => 'Bermain dengan melakonkan semula sesuatu watak (contoh: berlakon watak cikgu, doktor atau polis).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 114,
                'age_group' => 48,
                'domain' => 'kelakuan',
                'isCritical' => false,
                'description' => 'Membasuh atau mengeringkan tangan menggunakan kain atau tisu tanpa bantuan.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 115,
                'age_group' => 48,
                'domain' => 'kelakuan',
                'isCritical' => false,
                'description' => 'Boleh memberitahu nama sekurang-kurangnya dua orang kawan tidak termasuk adik-beradik.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 116,
                'age_group' => 48,
                'domain' => 'kognitif',
                'isCritical' => false,
                'description' => 'Boleh menggunakan blok atau kiub untuk membina menara atau beberapa jambatan daripada 10 atau lebih blok atau kiub.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 117,
                'age_group' => 48,
                'domain' => 'kognitif',
                'isCritical' => false,
                'description' => 'Boleh mengira lima objek yang dilihat satu persatu mengikut urutan (contoh: ‘ada 1, 2, 3, 4, 5 kereta’).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 118,
                'age_group' => 48,
                'domain' => 'kognitif',
                'isCritical' => false,
                'description' => 'Memahami konsep "sama" dan "berbeza" (contoh: "itik" dan "matahari" kuning, “ini baju, bukan seluar”).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],

            //Seeder for 60 months old
            [
                'id' => 119,
                'age_group' => 60,
                'domain' => 'motor_kasar',
                'isCritical' => false,
                'description' => 'Boleh berdiri dengan satu kaki selama 8 - 10 saat.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 120,
                'age_group' => 60,
                'domain' => 'motor_kasar',
                'isCritical' => true,
                'description' => 'Berskip (Skipping) menggunakan dua (2) kaki atau secara berselang seli.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 121,
                'age_group' => 60,
                'domain' => 'motor_kasar',
                'isCritical' => false,
                'description' => 'Membaling dan menangkap bola menggunakan kedua-dua tangan.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 122,
                'age_group' => 60,
                'domain' => 'motor_halus',
                'isCritical' => false,
                'description' => 'Boleh menggunting bentuk bulat atau segi empat tepat (petak).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 123,
                'age_group' => 60,
                'domain' => 'motor_halus',
                'isCritical' => false,
                'description' => 'Boleh membutang baju, membuka atau menutup zip pakaian sendiri.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 124,
                'age_group' => 60,
                'domain' => 'motor_halus',
                'isCritical' => false,
                'description' => 'Boleh melukis orang dengan sempurna (contoh: lukis orang yang mempunyai kepala, badan, tangan dan kaki).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 125,
                'age_group' => 60,
                'domain' => 'pertuturan_dan_bahasa',
                'isCritical' => false,
                'description' => 'Boleh memahami dan menggunakan konsep perbandingan (contoh: “kereta besar, tapi bas lagi besar”, “daun ringan, batu berat”).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 126,
                'age_group' => 60,
                'domain' => 'pertuturan_dan_bahasa',
                'isCritical' => false,
                'description' => 'Boleh mengulang ayat yang didengari (sekurang-kurangnya lima patah perkataan dan ke atas).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 127,
                'age_group' => 60,
                'domain' => 'pertuturan_dan_bahasa',
                'isCritical' => false,
                'description' => 'Boleh bertutur menggunakan empat hingga lima perkataan dalam satu ayat dengan tatabahasa dan bunyi sebutan yang betul (contoh: “Saya ternampak kereta berwarna kuning”).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 128,
                'age_group' => 60,
                'domain' => 'kelakuan',
                'isCritical' => false,
                'description' => 'Boleh mengambil giliran dan berkongsi barang dengan kanak-kanak lain.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 129,
                'age_group' => 60,
                'domain' => 'kelakuan',
                'isCritical' => false,
                'description' => 'Mempamerkan sikap mengambil berat terhadap orang lain atau adik beradik yang lebih muda.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 130,
                'age_group' => 60,
                'domain' => 'kelakuan',
                'isCritical' => false,
                'description' => 'Boleh menggunakan tandas tanpa bantuan.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 131,
                'age_group' => 60,
                'domain' => 'kognitif',
                'isCritical' => false,
                'description' => 'Boleh mengira satu hingga 15 mengikut turutan dengan betul.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 132,
                'age_group' => 60,
                'domain' => 'kognitif',
                'isCritical' => false,
                'description' => 'Boleh menyebut sekurang-kurangnya empat huruf pada nama sendiri apabila ditunjuk.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 133,
                'age_group' => 60,
                'domain' => 'kognitif',
                'isCritical' => false,
                'description' => 'Memahami konsep seperti masa (contoh: semalam, esok, sekarang dan lain-lain).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],

            //Seeder from 72 to 83 months old
            [
                'id' => 134,
                'age_group' => 72,
                'domain' => 'motor_kasar',
                'isCritical' => false,
                'description' => 'Boleh mengayuh dan menaiki basikal (dua roda).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 135,
                'age_group' => 72,
                'domain' => 'motor_kasar',
                'isCritical' => false,
                'description' => 'Boleh menangkap bola bersaiz lebih kecil (contoh: bola tenis, bola ping pong).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 136,
                'age_group' => 72,
                'domain' => 'motor_halus',
                'isCritical' => false,
                'description' => 'Boleh mewarna bentuk-bentuk mudah dengan kemas (tidak terkeluar dari garisan).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 137,
                'age_group' => 72,
                'domain' => 'motor_halus',
                'isCritical' => false,
                'description' => 'Boleh melukis bentuk asas tanpa melihat pada gambar bentuk.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 138,
                'age_group' => 72,
                'domain' => 'motor_halus',
                'isCritical' => false,
                'description' => 'Membuat ikatan menggunakan tali.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 139,
                'age_group' => 72,
                'domain' => 'pertuturan_dan_bahasa',
                'isCritical' => false,
                'description' => 'Boleh menceritakan semula cerita yang ditonton, didengari atau dibaca oleh orang lain (contoh: Watak dan jalan cerita yang ditonton).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 140,
                'age_group' => 72,
                'domain' => 'pertuturan_dan_bahasa',
                'isCritical' => true,
                'description' => 'Bercakap menggunakan bunyi sebutan yang jelas dan lancar (percakapan difahami oleh orang yang tidak dikenali).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 141,
                'age_group' => 72,
                'domain' => 'pertuturan_dan_bahasa',
                'isCritical' => false,
                'description' => 'Memahami dan suka kepada lawak jenaka dan tekateki.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 142,
                'age_group' => 72,
                'domain' => 'kelakuan',
                'isCritical' => true,
                'description' => 'Cuba untuk berkawan dengan kanak-kanak sebaya (contoh: Ajak kawan bermain “Jom main sama-sama”).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 143,
                'age_group' => 72,
                'domain' => 'kelakuan',
                'isCritical' => false,
                'description' => 'Menggunakan perkataan untuk meluahkan perasaan sendiri (contoh: Saya tak suka, saya takut lipas).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 144,
                'age_group' => 72,
                'domain' => 'kelakuan',
                'isCritical' => false,
                'description' => 'Memakai kasut pada kaki yang betul.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 145,
                'age_group' => 72,
                'domain' => 'kognitif',
                'isCritical' => false,
                'description' => 'Boleh menulis nombor, huruf besar atau kecil.',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 146,
                'age_group' => 72,
                'domain' => 'kognitif',
                'isCritical' => false,
                'description' => 'Membaca beberapa perkataan yang biasa dilihat (contoh: buku, bola, susu, ibu dan sebagainya).',
                'youtube_title' => 'unavailable',
                'key' => 'unavailable',
                'image_path' => $imagePath,   
            ],
            [
                'id' => 147,
                'age_group' => 72,
                'domain' => 'kognitif',
                'isCritical' => false,
                'description' => 'Menulis nama sendiri tanpa bantuan (contoh: Tulis nama pendek).',
                'youtube_title' => $imagePath,
                'key' => $imagePath,
                'image_path' => $imagePath,   
            ],
        ];

        foreach($milestones as $milestone){
            Milestone::firstOrCreate($milestone);
        }
    }
}
